# Generated by Django 5.1.4 on 2025-02-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedb',
            name='game_mode',
            field=models.CharField(blank=True, default='single', max_length=50),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='game_type',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='player1_rank_after_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='player1_rank_before_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='player2_rank_after_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='gamedb',
            name='player2_rank_before_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tmpgamedb',
            name='game_mode',
            field=models.CharField(blank=True, default='single', max_length=50),
        ),
        migrations.AddField(
            model_name='tmpgamedb',
            name='game_type',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='tmpgamedb',
            name='player1_rank_after_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tmpgamedb',
            name='player1_rank_before_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tmpgamedb',
            name='player2_rank_after_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tmpgamedb',
            name='player2_rank_before_game',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('player_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('event_details', models.JSONField(blank=True, null=True)),
                ('game_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gamedb')),
            ],
        ),
    ]
