# Generated by Django 5.1.4 on 2025-01-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendshiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'P')), fields=('sender', 'receiver'), name='unique_active_friendship_request'),
        ),
    ]
