# Generated by Django 5.1.4 on 2025-02-01 15:07

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendshiprequest_unique_active_friendship_request'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='.'),
        ),
    ]
