# Generated by Django 5.1.4 on 2025-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
